
  # Example static site config
  # - type: web
  #   name: my-blog
  #   runtime: static
  #   buildCommand: yarn build
  #   staticPublishPath: ./build
  #   previews:
  #     generation: automatic # Enable service previews
  #   buildFilter:
  #     paths:
  #       - src/**/*.js
  #     ignoredPaths:
  #       - src/**/*.test.js
  #   headers:
  #     - path: /*
  #       name: X-Frame-Options
  #       value: sameorigin
  #   routes:
  #     - type: redirect
  #       source: /old
  #       destination: /new
  #     - type: rewrite
  #       source: /a/*
  #       destination: /a

services:
  - type: web
    name: shell
    runtime: static
    rootDir: apps/shell
    buildCommand: npx nx build shell --configuration=production
    staticPublishPath: dist/apps/shell
    buildFilter:
      paths:
        - apps/shell/**
        - packages/**
    previews:
      generation: automatic
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache

  - type: web
    name: backend
    runtime: static
    rootDir: apps/backend
    buildCommand: npx nx build backend --configuration=production
    staticPublishPath: dist/apps/backend
    buildFilter:
      paths:
        - apps/backend/**
        - packages/**
    previews:
      generation: automatic
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache

  - type: web
    name: design
    runtime: static
    rootDir: apps/design
    buildCommand: npx nx build design --configuration=production
    staticPublishPath: ../../dist/apps/design
    buildFilter:
      paths:
        - apps/design/**
        - packages/**
    previews:
      generation: automatic
    headers:
      - path: /*
        name: Cache-Control 
        value: no-cache

  - type: web
    name: devops
    runtime: static
    rootDir: apps/devops
    buildCommand: npx nx build devops --configuration=production
    staticPublishPath: ../../dist/apps/devops
    buildFilter:
      paths:
        - apps/devops/**
        - packages/**
    previews:
      generation: automatic
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache

  - type: web
    name: dsa
    runtime: static
    rootDir: apps/dsa
    buildCommand: npx nx build dsa --configuration=production
    staticPublishPath: ../../dist/apps/dsa
    buildFilter:
      paths:
        - apps/dsa/**
        - packages/**
    previews:
      generation: automatic
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache

  - type: web
    name: frontend
    runtime: static
    rootDir: apps/frontend
    buildCommand: npx nx build frontend --configuration=production
    staticPublishPath: ../../dist/apps/frontend
    buildFilter:
      paths:
        - apps/frontend/**
        - packages/**
    previews:
      generation: automatic
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache

  - type: web
    name: home
    runtime: static
    rootDir: apps/home
    buildCommand: npx nx build home --configuration=production
    staticPublishPath: ../../dist/apps/home
    buildFilter:
      paths:
        - apps/home/**
        - packages/**
    previews:
      generation: automatic
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache