# Example static site config
# - type: web
#   name: my-blog
#   runtime: static
#   buildCommand: yarn build
#   staticPublishPath: ./build
#   previews:
#     generation: automatic # Enable service previews
#   buildFilter:
#     paths:
#       - src/**/*.js
#     ignoredPaths:
#       - src/**/*.test.js
#   headers:
#     - path: /*
#       name: X-Frame-Options
#       value: sameorigin
#   routes:
#     - type: redirect
#       source: /old
#       destination: /new
#     - type: rewrite
#       source: /a/*
#       destination: /a

services:
  - type: web
    name: router
    runtime: static
    rootDir: apps/router
    buildCommand: npm install && npx nx build router --configuration=production
    staticPublishPath: dist/apps/router
    branch: main
    autoDeploy: true
    buildFilter:
      paths:
        - apps/router/**
        - libs/**
    previews:
      generation: automatic
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache

  - type: web
    name: home
    runtime: static
    rootDir: apps/home
    buildCommand: npm install && npx nx build home --configuration=production
    staticPublishPath: dist/apps/home
    branch: main
    autoDeploy: true
    buildFilter:
      paths:
        - apps/home/**
        - libs/**
    previews:
      generation: automatic
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
