name: build

on:
  pull_request:
    branches: [main]

jobs:
  detect-affected:
    uses: ./.github/workflows/detect-affected.yml
    with:
      target: build

  build:
    needs: detect-affected
    if: ${{ needs.detect-affected.outputs.apps != '[]' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: ${{ fromJson(needs.detect-affected.outputs.apps) }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build ${{ matrix.app }}
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
          NX_RUN_GROUP: ${{ github.run_id }}
        run: npx nx build ${{ matrix.app }} --configuration=production

      - name: Upload affected apps
        uses: actions/upload-artifact@v4
        with:
          name: affected-apps
          path: affected.json
