name: Build Prod Client

on:
  push:
    branches:
      - prod-client

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build
        run: |
          bun install
          bun run build:client

      - name: Merge to main
        run: |
          git checkout main
          git merge prod-client
          git push
