name: Draft Releases
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  detect-affected:
    uses: ./.github/workflows/detect-affected.yml
    with:
      base: ${{ github.event.before }}
      target: build

  release:
    needs: detect-affected
    if: ${{ needs.detect-affected.outputs.apps != '[]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci

      - name: Disable Husky and setup Git
        run: |
          export HUSKY=0
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global core.hooksPath /dev/null
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Create Release Drafts for affected apps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          apps='${{ needs.detect-affected.outputs.apps }}'
          echo "🚀 Starting smart releases for apps: $apps"

          # Use our new smart release workflow
          if HUSKY=0 npm run release:smart --base=${{ github.event.before }}; then
            echo "✅ Successfully released all affected apps"
          else
            echo "❌ Failed to release apps"
            exit 1
          fi

      - name: Push version bumps and tags
        run: |
          # Push all commits and tags together
          git push --follow-tags origin main
