name: Release shell
on:
  push:
    branches: [main]
    paths: ['apps/shell/**']

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci

      - name: Git setup
        run: |
          git config --global user.name  "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global core.hooksPath /dev/null
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Release shell
        working-directory: apps/shell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx release-it --ci

      - name: Push changes with retry logic (max 10 tries)
        env: { MAX_RETRIES: 10 }
        run: |
          set -e
          n=0
          while \! git push --follow-tags --no-verify; do
            n=$((n+1))
            if [ "$n" -ge "$MAX_RETRIES" ]; then
              echo "❌  Push failed after $MAX_RETRIES attempts"; exit 1
            fi
            echo "⚠️   main moved — re-basing (attempt $n)…"
            sleep $((n * 2))  # Exponential backoff
            git fetch origin main
            git rebase origin/main
          done
          echo "✅  Push succeeded after $n re-tries"
